Repository OkMoK-co/OkMoK, pull requests merged in 2023-03, with the labels that each got.

#17 Feat/next환경재구축#16
  hybrid/.vscode/settings.json
  hybrid/README.md
  hybrid/config/db.ts
  hybrid/next.config.js
  hybrid/package-lock.json
  hybrid/package.json
  hybrid/src/apollo/resolver.ts
  hybrid/src/apollo/schema.ts
  hybrid/src/apollo/typeDefs.ts
  hybrid/src/app/(main)/layout.tsx
  hybrid/src/app/(main)/page.tsx
  hybrid/src/app/(main)/profile/page.tsx
  hybrid/src/app/(main)/rank/page.tsx
  hybrid/src/app/(main)/record/page.tsx
  hybrid/src/app/game/layout.tsx
  hybrid/src/app/head.tsx
  hybrid/src/app/layout.tsx
  hybrid/src/components/layout/DesktopChat.tsx
  hybrid/src/components/layout/DesktopLayout.tsx
  hybrid/src/components/layout/DesktopNav.tsx
  hybrid/src/components/layout/DesktopTaskBar.tsx
  hybrid/src/components/layout/Footer.tsx
  hybrid/src/components/layout/Header.tsx
  hybrid/src/components/layout/MainLayout.tsx
  hybrid/src/components/layout/MobileChat.tsx
  hybrid/src/components/layout/MobileLayout.tsx
  hybrid/src/components/layout/MobileNav.tsx
  hybrid/src/components/layout/NavBar.tsx
  hybrid/src/components/main/MakeRoom.tsx
  hybrid/src/components/main/RoomItem.tsx
  hybrid/src/components/main/Rooms.tsx
  hybrid/src/components/main/SearchBar.tsx
  hybrid/src/components/provider/Apollo.tsx
  hybrid/src/components/record/RecordItem.tsx
  hybrid/src/components/record/SearchDetail.tsx
  hybrid/src/components/record/SearchName.tsx
  hybrid/src/components/record/Tag.tsx
  hybrid/src/components/record/Tags.tsx
  hybrid/src/pages/_app.tsx
  hybrid/src/pages/_document.tsx
  hybrid/src/pages/api/graphql.ts
  hybrid/src/pages/game.tsx
  hybrid/src/pages/index.tsx
  hybrid/src/pages/login.tsx
  hybrid/src/styles/_common.scss
  hybrid/src/styles/layout/DesktopLayout.module.scss
  hybrid/src/styles/main/Main.module.scss
  hybrid/src/styles/main/Rooms.module.scss
  hybrid/src/styles/record/Record.module.scss
  hybrid/tsconfig.json
Labels: client

#19 Feat/styled component설치 #16
  hybrid/next.config.js
  hybrid/package-lock.json
  hybrid/package.json
  hybrid/src/pages/_app.tsx
  hybrid/src/pages/_document.tsx
  hybrid/src/pages/game.tsx
  hybrid/src/styles/_global.scss
  hybrid/src/styles/global-style.tsx
  hybrid/src/styles/style.d.ts
  hybrid/src/styles/theme.ts
Labels: client

#21 [Fix] warning으로 Head 위치 수정
  hybrid/src/pages/_app.tsx
  hybrid/src/pages/_document.tsx
Labels: client

#22 Feat/게임페이지정적뷰#18
  hybrid/src/components/game/GiveupButton.tsx
  hybrid/src/components/game/KickoutButton.tsx
  hybrid/src/components/game/OmokBoard.tsx
  hybrid/src/components/game/Players.tsx
  hybrid/src/components/game/Timer.tsx
  hybrid/src/components/layout/GameLayout.tsx
  hybrid/src/pages/game.tsx
Labels: client

#15 [Feat] WebSocketServer 클래스 구현 close #14
  socketserver/app/srcs/.gitkeep
  socketserver/app/srcs/main.cpp
  socketserver/app/srcs/server/WebSocketServer.cpp
  socketserver/app/srcs/server/WebSocketServer.hpp
Labels: c++ server

#29 [Feat] 플레이버튼 클릭 시 게임페이지 이동 #28
  hybrid/package-lock.json
  hybrid/package.json
  hybrid/src/components/layout/SocketConnect.tsx
  hybrid/src/components/main/PlayButton.tsx
  hybrid/src/pages/_app.tsx
  hybrid/src/pages/game.tsx
  hybrid/src/pages/index.tsx
  hybrid/src/socket/requestHandler.tsx
  hybrid/src/socket/responseHandler.tsx
  hybrid/src/socket/routeSocketFunction.ts
  hybrid/src/utils/recoil/socket.ts
  hybrid/src/utils/type/socketType.ts
  socketserver/app/srcs/packet/PacketManager.cpp
  socketserver/app/srcs/packet/PacketManager.hpp
Labels: client, c++ server

#27 [Refactor] check_install 스크립트 수정 close #26
  socketserver/scripts/check_install.sh
Labels: client

#33 [Refactor] 프론트 selector로 데이터 관리 및 백 run 실행시간 지연 수정 #28
  hybrid/src/components/layout/SocketConnect.tsx
  hybrid/src/components/main/PlayButton.tsx
  hybrid/src/components/main/Rooms.tsx
  hybrid/src/pages/index.tsx
  hybrid/src/socket/responseHandler.tsx
  hybrid/src/socket/routeSocketFunction.ts
  hybrid/src/socket/variable.ts
  hybrid/src/utils/recoil/socket.ts
  hybrid/src/utils/type/socketType.ts
  socketserver/app/srcs/user/UserManager.cpp
Labels: client, c++ server
